// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFWJ44wO1EYVRiikLnLja9IxpJBlXpMmk',
    appId: '1:178337801782:web:b92bdebb8050cb3646da97',
    messagingSenderId: '178337801782',
    projectId: 'companion-43944',
    authDomain: 'companion-43944.firebaseapp.com',
    storageBucket: 'companion-43944.appspot.com',
    measurementId: 'G-NT6GX96VJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtSalJ0NacokKHVEKozXi89dZxEp7VhII',
    appId: '1:178337801782:android:9013d7e9b7a1f90d46da97',
    messagingSenderId: '178337801782',
    projectId: 'companion-43944',
    storageBucket: 'companion-43944.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3bhkzRcpKf0ndo_wRKg7RY2XShwg3QEU',
    appId: '1:178337801782:ios:234f986871cc049146da97',
    messagingSenderId: '178337801782',
    projectId: 'companion-43944',
    storageBucket: 'companion-43944.appspot.com',
    iosClientId: '178337801782-ds74m73n7t4d043phs98qupg354v3pnb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
